version: '3'

services:
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: myuser
      MYSQL_PASSWORD: root

  nodejs-api:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
